/* C Abstract Syntax Implementation generated by the BNF Converter. */

#include <stdio.h>
#include <stdlib.h>
#include "Absyn.h"

/********************   Prog    ********************/

Program make_Prog(ListTopDef p1)
{
    Program tmp = (Program) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Prog!\n");
        exit(1);
    }
    tmp->kind = is_Prog;
    tmp->u.prog_.listtopdef_ = p1;
    return tmp;
}

/********************   FnDef    ********************/

TopDef make_FnDef(Type p1, Ident p2, ListArg p3, Block p4)
{
    TopDef tmp = (TopDef) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating FnDef!\n");
        exit(1);
    }
    tmp->kind = is_FnDef;
    tmp->u.fndef_.type_ = p1;
    tmp->u.fndef_.ident_ = p2;
    tmp->u.fndef_.listarg_ = p3;
    tmp->u.fndef_.block_ = p4;
    return tmp;
}

/********************   ClassDef    ********************/

TopDef make_ClassDef(Ident p1, ClassBlock p2)
{
    TopDef tmp = (TopDef) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ClassDef!\n");
        exit(1);
    }
    tmp->kind = is_ClassDef;
    tmp->u.classdef_.ident_ = p1;
    tmp->u.classdef_.classblock_ = p2;
    return tmp;
}

/********************   ClassDefExt    ********************/

TopDef make_ClassDefExt(Ident p1, Ident p2, ClassBlock p3)
{
    TopDef tmp = (TopDef) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ClassDefExt!\n");
        exit(1);
    }
    tmp->kind = is_ClassDefExt;
    tmp->u.classdefext_.ident_1 = p1;
    tmp->u.classdefext_.ident_2 = p2;
    tmp->u.classdefext_.classblock_ = p3;
    return tmp;
}

/********************   ListTopDef    ********************/

ListTopDef make_ListTopDef(TopDef p1, ListTopDef p2)
{
    ListTopDef tmp = (ListTopDef) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListTopDef!\n");
        exit(1);
    }
    tmp->topdef_ = p1;
    tmp->listtopdef_ = p2;
    return tmp;
}

/********************   Ar    ********************/

Arg make_Ar(Type p1, Ident p2)
{
    Arg tmp = (Arg) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Ar!\n");
        exit(1);
    }
    tmp->kind = is_Ar;
    tmp->u.ar_.type_ = p1;
    tmp->u.ar_.ident_ = p2;
    return tmp;
}

/********************   ListArg    ********************/

ListArg make_ListArg(Arg p1, ListArg p2)
{
    ListArg tmp = (ListArg) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListArg!\n");
        exit(1);
    }
    tmp->arg_ = p1;
    tmp->listarg_ = p2;
    return tmp;
}

/********************   ClassBlk    ********************/

ClassBlock make_ClassBlk(ListClassDecl p1)
{
    ClassBlock tmp = (ClassBlock) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ClassBlk!\n");
        exit(1);
    }
    tmp->kind = is_ClassBlk;
    tmp->u.classblk_.listclassdecl_ = p1;
    return tmp;
}

/********************   ListClassDecl    ********************/

ListClassDecl make_ListClassDecl(ClassDecl p1, ListClassDecl p2)
{
    ListClassDecl tmp = (ListClassDecl) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListClassDecl!\n");
        exit(1);
    }
    tmp->classdecl_ = p1;
    tmp->listclassdecl_ = p2;
    return tmp;
}

/********************   FieldDecl    ********************/

ClassDecl make_FieldDecl(Type p1, ListIdent p2)
{
    ClassDecl tmp = (ClassDecl) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating FieldDecl!\n");
        exit(1);
    }
    tmp->kind = is_FieldDecl;
    tmp->u.fielddecl_.type_ = p1;
    tmp->u.fielddecl_.listident_ = p2;
    return tmp;
}

/********************   MethodDecl    ********************/

ClassDecl make_MethodDecl(Type p1, Ident p2, ListArg p3, Block p4)
{
    ClassDecl tmp = (ClassDecl) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating MethodDecl!\n");
        exit(1);
    }
    tmp->kind = is_MethodDecl;
    tmp->u.methoddecl_.type_ = p1;
    tmp->u.methoddecl_.ident_ = p2;
    tmp->u.methoddecl_.listarg_ = p3;
    tmp->u.methoddecl_.block_ = p4;
    return tmp;
}

/********************   ListIdent    ********************/

ListIdent make_ListIdent(Ident p1, ListIdent p2)
{
    ListIdent tmp = (ListIdent) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListIdent!\n");
        exit(1);
    }
    tmp->ident_ = p1;
    tmp->listident_ = p2;
    return tmp;
}

/********************   Blk    ********************/

Block make_Blk(ListStmt p1)
{
    Block tmp = (Block) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Blk!\n");
        exit(1);
    }
    tmp->kind = is_Blk;
    tmp->u.blk_.liststmt_ = p1;
    return tmp;
}

/********************   ListStmt    ********************/

ListStmt make_ListStmt(Stmt p1, ListStmt p2)
{
    ListStmt tmp = (ListStmt) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListStmt!\n");
        exit(1);
    }
    tmp->stmt_ = p1;
    tmp->liststmt_ = p2;
    return tmp;
}

/********************   Empty    ********************/

Stmt make_Empty()
{
    Stmt tmp = (Stmt) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Empty!\n");
        exit(1);
    }
    tmp->kind = is_Empty;
    return tmp;
}

/********************   BStmt    ********************/

Stmt make_BStmt(Block p1)
{
    Stmt tmp = (Stmt) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating BStmt!\n");
        exit(1);
    }
    tmp->kind = is_BStmt;
    tmp->u.bstmt_.block_ = p1;
    return tmp;
}

/********************   Decl    ********************/

Stmt make_Decl(Type p1, ListItem p2)
{
    Stmt tmp = (Stmt) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Decl!\n");
        exit(1);
    }
    tmp->kind = is_Decl;
    tmp->u.decl_.type_ = p1;
    tmp->u.decl_.listitem_ = p2;
    return tmp;
}

/********************   Ass    ********************/

Stmt make_Ass(Expr p1, Expr p2)
{
    Stmt tmp = (Stmt) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Ass!\n");
        exit(1);
    }
    tmp->kind = is_Ass;
    tmp->u.ass_.expr_1 = p1;
    tmp->u.ass_.expr_2 = p2;
    return tmp;
}

/********************   Incr    ********************/

Stmt make_Incr(Expr p1)
{
    Stmt tmp = (Stmt) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Incr!\n");
        exit(1);
    }
    tmp->kind = is_Incr;
    tmp->u.incr_.expr_ = p1;
    return tmp;
}

/********************   Decr    ********************/

Stmt make_Decr(Expr p1)
{
    Stmt tmp = (Stmt) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Decr!\n");
        exit(1);
    }
    tmp->kind = is_Decr;
    tmp->u.decr_.expr_ = p1;
    return tmp;
}

/********************   Ret    ********************/

Stmt make_Ret(Expr p1)
{
    Stmt tmp = (Stmt) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Ret!\n");
        exit(1);
    }
    tmp->kind = is_Ret;
    tmp->u.ret_.expr_ = p1;
    return tmp;
}

/********************   VRet    ********************/

Stmt make_VRet()
{
    Stmt tmp = (Stmt) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating VRet!\n");
        exit(1);
    }
    tmp->kind = is_VRet;
    return tmp;
}

/********************   Cond    ********************/

Stmt make_Cond(Expr p1, Stmt p2)
{
    Stmt tmp = (Stmt) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Cond!\n");
        exit(1);
    }
    tmp->kind = is_Cond;
    tmp->u.cond_.expr_ = p1;
    tmp->u.cond_.stmt_ = p2;
    return tmp;
}

/********************   CondElse    ********************/

Stmt make_CondElse(Expr p1, Stmt p2, Stmt p3)
{
    Stmt tmp = (Stmt) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating CondElse!\n");
        exit(1);
    }
    tmp->kind = is_CondElse;
    tmp->u.condelse_.expr_ = p1;
    tmp->u.condelse_.stmt_1 = p2;
    tmp->u.condelse_.stmt_2 = p3;
    return tmp;
}

/********************   While    ********************/

Stmt make_While(Expr p1, Stmt p2)
{
    Stmt tmp = (Stmt) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating While!\n");
        exit(1);
    }
    tmp->kind = is_While;
    tmp->u.while_.expr_ = p1;
    tmp->u.while_.stmt_ = p2;
    return tmp;
}

/********************   For    ********************/

Stmt make_For(TypeSimple p1, Ident p2, Expr p3, Stmt p4)
{
    Stmt tmp = (Stmt) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating For!\n");
        exit(1);
    }
    tmp->kind = is_For;
    tmp->u.for_.typesimple_ = p1;
    tmp->u.for_.ident_ = p2;
    tmp->u.for_.expr_ = p3;
    tmp->u.for_.stmt_ = p4;
    return tmp;
}

/********************   SExp    ********************/

Stmt make_SExp(Expr p1)
{
    Stmt tmp = (Stmt) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating SExp!\n");
        exit(1);
    }
    tmp->kind = is_SExp;
    tmp->u.sexp_.expr_ = p1;
    return tmp;
}

/********************   NoInit    ********************/

Item make_NoInit(Ident p1)
{
    Item tmp = (Item) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating NoInit!\n");
        exit(1);
    }
    tmp->kind = is_NoInit;
    tmp->u.noinit_.ident_ = p1;
    return tmp;
}

/********************   Init    ********************/

Item make_Init(Ident p1, Expr p2)
{
    Item tmp = (Item) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Init!\n");
        exit(1);
    }
    tmp->kind = is_Init;
    tmp->u.init_.ident_ = p1;
    tmp->u.init_.expr_ = p2;
    return tmp;
}

/********************   ListItem    ********************/

ListItem make_ListItem(Item p1, ListItem p2)
{
    ListItem tmp = (ListItem) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListItem!\n");
        exit(1);
    }
    tmp->item_ = p1;
    tmp->listitem_ = p2;
    return tmp;
}

/********************   Int    ********************/

TypeSimple make_Int()
{
    TypeSimple tmp = (TypeSimple) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Int!\n");
        exit(1);
    }
    tmp->kind = is_Int;
    return tmp;
}

/********************   Str    ********************/

TypeSimple make_Str()
{
    TypeSimple tmp = (TypeSimple) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Str!\n");
        exit(1);
    }
    tmp->kind = is_Str;
    return tmp;
}

/********************   Bool    ********************/

TypeSimple make_Bool()
{
    TypeSimple tmp = (TypeSimple) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Bool!\n");
        exit(1);
    }
    tmp->kind = is_Bool;
    return tmp;
}

/********************   Class    ********************/

TypeSimple make_Class(Ident p1)
{
    TypeSimple tmp = (TypeSimple) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Class!\n");
        exit(1);
    }
    tmp->kind = is_Class;
    tmp->u.class_.ident_ = p1;
    return tmp;
}

/********************   Void    ********************/

Type make_Void()
{
    Type tmp = (Type) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Void!\n");
        exit(1);
    }
    tmp->kind = is_Void;
    return tmp;
}

/********************   SingleType    ********************/

Type make_SingleType(TypeSimple p1)
{
    Type tmp = (Type) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating SingleType!\n");
        exit(1);
    }
    tmp->kind = is_SingleType;
    tmp->u.singletype_.typesimple_ = p1;
    return tmp;
}

/********************   ArrayType    ********************/

Type make_ArrayType(TypeSimple p1)
{
    Type tmp = (Type) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ArrayType!\n");
        exit(1);
    }
    tmp->kind = is_ArrayType;
    tmp->u.arraytype_.typesimple_ = p1;
    return tmp;
}

/********************   ListType    ********************/

ListType make_ListType(Type p1, ListType p2)
{
    ListType tmp = (ListType) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListType!\n");
        exit(1);
    }
    tmp->type_ = p1;
    tmp->listtype_ = p2;
    return tmp;
}

/********************   FieldValCall    ********************/

FieldVal make_FieldValCall(Ident p1, ListExpr p2)
{
    FieldVal tmp = (FieldVal) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating FieldValCall!\n");
        exit(1);
    }
    tmp->kind = is_FieldValCall;
    tmp->u.fieldvalcall_.ident_ = p1;
    tmp->u.fieldvalcall_.listexpr_ = p2;
    return tmp;
}

/********************   FieldValSingle    ********************/

FieldVal make_FieldValSingle(Ident p1)
{
    FieldVal tmp = (FieldVal) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating FieldValSingle!\n");
        exit(1);
    }
    tmp->kind = is_FieldValSingle;
    tmp->u.fieldvalsingle_.ident_ = p1;
    return tmp;
}

/********************   FieldSingle    ********************/

Field make_FieldSingle(FieldVal p1)
{
    Field tmp = (Field) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating FieldSingle!\n");
        exit(1);
    }
    tmp->kind = is_FieldSingle;
    tmp->u.fieldsingle_.fieldval_ = p1;
    return tmp;
}

/********************   FieldArray    ********************/

Field make_FieldArray(FieldVal p1, Expr p2)
{
    Field tmp = (Field) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating FieldArray!\n");
        exit(1);
    }
    tmp->kind = is_FieldArray;
    tmp->u.fieldarray_.fieldval_ = p1;
    tmp->u.fieldarray_.expr_ = p2;
    return tmp;
}

/********************   FieldSelf    ********************/

Field make_FieldSelf()
{
    Field tmp = (Field) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating FieldSelf!\n");
        exit(1);
    }
    tmp->kind = is_FieldSelf;
    return tmp;
}

/********************   ListField    ********************/

ListField make_ListField(Field p1, ListField p2)
{
    ListField tmp = (ListField) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListField!\n");
        exit(1);
    }
    tmp->field_ = p1;
    tmp->listfield_ = p2;
    return tmp;
}

/********************   ENewObject    ********************/

Expr make_ENewObject(Ident p1)
{
    Expr tmp = (Expr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ENewObject!\n");
        exit(1);
    }
    tmp->kind = is_ENewObject;
    tmp->u.enewobject_.ident_ = p1;
    return tmp;
}

/********************   ENewArray    ********************/

Expr make_ENewArray(TypeSimple p1, Expr p2)
{
    Expr tmp = (Expr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ENewArray!\n");
        exit(1);
    }
    tmp->kind = is_ENewArray;
    tmp->u.enewarray_.typesimple_ = p1;
    tmp->u.enewarray_.expr_ = p2;
    return tmp;
}

/********************   ETmpVar    ********************/

Expr make_ETmpVar(Expr p1, ListField p2)
{
    Expr tmp = (Expr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ETmpVar!\n");
        exit(1);
    }
    tmp->kind = is_ETmpVar;
    tmp->u.etmpvar_.expr_ = p1;
    tmp->u.etmpvar_.listfield_ = p2;
    return tmp;
}

/********************   ETmpArrayElem    ********************/

Expr make_ETmpArrayElem(Expr p1, Expr p2)
{
    Expr tmp = (Expr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ETmpArrayElem!\n");
        exit(1);
    }
    tmp->kind = is_ETmpArrayElem;
    tmp->u.etmparrayelem_.expr_1 = p1;
    tmp->u.etmparrayelem_.expr_2 = p2;
    return tmp;
}

/********************   ETmpArrayElemVar    ********************/

Expr make_ETmpArrayElemVar(Expr p1, Expr p2, ListField p3)
{
    Expr tmp = (Expr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ETmpArrayElemVar!\n");
        exit(1);
    }
    tmp->kind = is_ETmpArrayElemVar;
    tmp->u.etmparrayelemvar_.expr_1 = p1;
    tmp->u.etmparrayelemvar_.expr_2 = p2;
    tmp->u.etmparrayelemvar_.listfield_ = p3;
    return tmp;
}

/********************   ECastedNull    ********************/

Expr make_ECastedNull(Expr p1)
{
    Expr tmp = (Expr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ECastedNull!\n");
        exit(1);
    }
    tmp->kind = is_ECastedNull;
    tmp->u.ecastednull_.expr_ = p1;
    return tmp;
}

/********************   ECastedArrNull    ********************/

Expr make_ECastedArrNull(TypeSimple p1)
{
    Expr tmp = (Expr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ECastedArrNull!\n");
        exit(1);
    }
    tmp->kind = is_ECastedArrNull;
    tmp->u.ecastedarrnull_.typesimple_ = p1;
    return tmp;
}

/********************   ENull    ********************/

Expr make_ENull()
{
    Expr tmp = (Expr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ENull!\n");
        exit(1);
    }
    tmp->kind = is_ENull;
    return tmp;
}

/********************   EVar    ********************/

Expr make_EVar(ListField p1)
{
    Expr tmp = (Expr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EVar!\n");
        exit(1);
    }
    tmp->kind = is_EVar;
    tmp->u.evar_.listfield_ = p1;
    return tmp;
}

/********************   ELitInt    ********************/

Expr make_ELitInt(Integer p1)
{
    Expr tmp = (Expr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ELitInt!\n");
        exit(1);
    }
    tmp->kind = is_ELitInt;
    tmp->u.elitint_.integer_ = p1;
    return tmp;
}

/********************   ELitTrue    ********************/

Expr make_ELitTrue()
{
    Expr tmp = (Expr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ELitTrue!\n");
        exit(1);
    }
    tmp->kind = is_ELitTrue;
    return tmp;
}

/********************   ELitFalse    ********************/

Expr make_ELitFalse()
{
    Expr tmp = (Expr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ELitFalse!\n");
        exit(1);
    }
    tmp->kind = is_ELitFalse;
    return tmp;
}

/********************   EString    ********************/

Expr make_EString(String p1)
{
    Expr tmp = (Expr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EString!\n");
        exit(1);
    }
    tmp->kind = is_EString;
    tmp->u.estring_.string_ = p1;
    return tmp;
}

/********************   Neg    ********************/

Expr make_Neg(Expr p1)
{
    Expr tmp = (Expr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Neg!\n");
        exit(1);
    }
    tmp->kind = is_Neg;
    tmp->u.neg_.expr_ = p1;
    return tmp;
}

/********************   Not    ********************/

Expr make_Not(Expr p1)
{
    Expr tmp = (Expr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Not!\n");
        exit(1);
    }
    tmp->kind = is_Not;
    tmp->u.not_.expr_ = p1;
    return tmp;
}

/********************   EMul    ********************/

Expr make_EMul(Expr p1, MulOp p2, Expr p3)
{
    Expr tmp = (Expr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EMul!\n");
        exit(1);
    }
    tmp->kind = is_EMul;
    tmp->u.emul_.expr_1 = p1;
    tmp->u.emul_.mulop_ = p2;
    tmp->u.emul_.expr_2 = p3;
    return tmp;
}

/********************   EAdd    ********************/

Expr make_EAdd(Expr p1, AddOp p2, Expr p3)
{
    Expr tmp = (Expr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EAdd!\n");
        exit(1);
    }
    tmp->kind = is_EAdd;
    tmp->u.eadd_.expr_1 = p1;
    tmp->u.eadd_.addop_ = p2;
    tmp->u.eadd_.expr_2 = p3;
    return tmp;
}

/********************   ERel    ********************/

Expr make_ERel(Expr p1, RelOp p2, Expr p3)
{
    Expr tmp = (Expr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ERel!\n");
        exit(1);
    }
    tmp->kind = is_ERel;
    tmp->u.erel_.expr_1 = p1;
    tmp->u.erel_.relop_ = p2;
    tmp->u.erel_.expr_2 = p3;
    return tmp;
}

/********************   EAnd    ********************/

Expr make_EAnd(Expr p1, Expr p2)
{
    Expr tmp = (Expr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EAnd!\n");
        exit(1);
    }
    tmp->kind = is_EAnd;
    tmp->u.eand_.expr_1 = p1;
    tmp->u.eand_.expr_2 = p2;
    return tmp;
}

/********************   EOr    ********************/

Expr make_EOr(Expr p1, Expr p2)
{
    Expr tmp = (Expr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EOr!\n");
        exit(1);
    }
    tmp->kind = is_EOr;
    tmp->u.eor_.expr_1 = p1;
    tmp->u.eor_.expr_2 = p2;
    return tmp;
}

/********************   ListExpr    ********************/

ListExpr make_ListExpr(Expr p1, ListExpr p2)
{
    ListExpr tmp = (ListExpr) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListExpr!\n");
        exit(1);
    }
    tmp->expr_ = p1;
    tmp->listexpr_ = p2;
    return tmp;
}

/********************   Plus    ********************/

AddOp make_Plus()
{
    AddOp tmp = (AddOp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Plus!\n");
        exit(1);
    }
    tmp->kind = is_Plus;
    return tmp;
}

/********************   Minus    ********************/

AddOp make_Minus()
{
    AddOp tmp = (AddOp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Minus!\n");
        exit(1);
    }
    tmp->kind = is_Minus;
    return tmp;
}

/********************   Times    ********************/

MulOp make_Times()
{
    MulOp tmp = (MulOp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Times!\n");
        exit(1);
    }
    tmp->kind = is_Times;
    return tmp;
}

/********************   Div    ********************/

MulOp make_Div()
{
    MulOp tmp = (MulOp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Div!\n");
        exit(1);
    }
    tmp->kind = is_Div;
    return tmp;
}

/********************   Mod    ********************/

MulOp make_Mod()
{
    MulOp tmp = (MulOp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Mod!\n");
        exit(1);
    }
    tmp->kind = is_Mod;
    return tmp;
}

/********************   LTH    ********************/

RelOp make_LTH()
{
    RelOp tmp = (RelOp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating LTH!\n");
        exit(1);
    }
    tmp->kind = is_LTH;
    return tmp;
}

/********************   LE    ********************/

RelOp make_LE()
{
    RelOp tmp = (RelOp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating LE!\n");
        exit(1);
    }
    tmp->kind = is_LE;
    return tmp;
}

/********************   GTH    ********************/

RelOp make_GTH()
{
    RelOp tmp = (RelOp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating GTH!\n");
        exit(1);
    }
    tmp->kind = is_GTH;
    return tmp;
}

/********************   GE    ********************/

RelOp make_GE()
{
    RelOp tmp = (RelOp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating GE!\n");
        exit(1);
    }
    tmp->kind = is_GE;
    return tmp;
}

/********************   EQU    ********************/

RelOp make_EQU()
{
    RelOp tmp = (RelOp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EQU!\n");
        exit(1);
    }
    tmp->kind = is_EQU;
    return tmp;
}

/********************   NE    ********************/

RelOp make_NE()
{
    RelOp tmp = (RelOp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating NE!\n");
        exit(1);
    }
    tmp->kind = is_NE;
    return tmp;
}
